apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  labels:
    app: blog-web
spec:
  selector:
    matchLabels:
      app: blog-web
  #   replicas: 3
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
        - image: repo.kinesis.games:5050/react/blog:latest
          name: blog-web
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.2
      imagePullSecrets:
        - name: regcred
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-web
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  labels:
    app: blog-web
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30003
      protocol: TCP
  selector:
    app: blog-web
